<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
       name="agv2" >

  <!-- common stuff -->
  <xacro:include filename="$(find agv2_description)/urdf/agv2.gazebo.xacro" />
  <xacro:include filename="$(find agv2_description)/urdf/common.xacro" />
  <xacro:include filename="$(find agv2_description)/urdf/materials.urdf.xacro" />
  <xacro:include filename="$(find agv2_description)/urdf/controller.gazebo" />
  <xacro:include filename="$(find agv2_description)/urdf/wheel_agv.urdf.xacro" />
  <xacro:include filename="$(find agv2_description)/urdf/laser.urdf.xacro" />
  <xacro:include filename="$(find agv2_description)/urdf/laser.gazebo.xacro" />

  <link name="base_footprint"/>

  <!-- Base -->
  <property name="agv_height" value="0.268" />
  <property name="hollow_h" value="0.01" />
  <joint name="base_joint" type="fixed">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" velocity="0.5"/>
    <origin xyz="0 0 ${agv_height/2 + hollow_h}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  <link name="base_link">
<!--
    <xacro:box_inertial mass="50" x="0.645" y="1.099" z="0.28">
      <origin rpy="0 0 ${M_PI/2}" xyz="0 0 0" />
    </xacro:box_inertial>
-->
    <inertial>
      <origin rpy="0 0 ${M_PI/2}" xyz="0 0 0"/>
      <mass value="50.0"/>
      <inertia ixx="0.007081" ixy="-0.000118" ixz="-7.4538e-07" iyy="0.017373" iyz="0.000001" izz="0.022258"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
        <geometry>
          <mesh filename="package://agv2_description/meshes/agv_black.dae" />
        </geometry>
      <material name="YellowRubber"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
        <geometry>
          <mesh filename="package://agv2_description/meshes/agv_black.stl" />
        </geometry>
    </collision>
  </link>

  <!-- rod front -->
  <property name="rod_r" value="0.0136" />
  <property name="rod_h" value="0.060" />
  <joint name="rod_front_joint" type="prismatic">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" velocity="0.5" lower="0" upper="${rod_h}"/>
    <origin xyz="0 -0.398 ${agv_height/2 - rod_h/2}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="rod_front_link" />
  </joint>

  <link name="rod_front_link">
        <xacro:cylinder_inertial mass="0.1" radius="${rod_r}" length="${rod_h}">
          <origin rpy="0 0 0" xyz="0 0 0" />
        </xacro:cylinder_inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${rod_h}" radius="${rod_r}"/>
        </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${rod_h}" radius="${rod_r}"/>
        </geometry>
    </collision>
  </link>
  <!-- rod rares -->
  <joint name="rod_rare_joint" type="prismatic">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" velocity="0.5" lower="0" upper="${rod_h}"/>
    <origin xyz="0 0.340 ${agv_height/2 - rod_h/2}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="rod_rare_link" />
  </joint>

  <link name="rod_rare_link">
        <xacro:cylinder_inertial mass="0.1" radius="${rod_r}" length="${rod_h}">
          <origin rpy="0 0 0" xyz="0 0 0" />
        </xacro:cylinder_inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${rod_h}" radius="${rod_r}"/>
        </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${rod_h}" radius="${rod_r}"/>
        </geometry>
    </collision>
  </link>
  <!-- wheel -->
  <property name="BASE_R" value="0.251"/>
  <property name="BASE_DUMMY_R" value="0.225"/>
  <property name="drive_wheel_r" value="0.08" />
  <xacro:wheel name="l_wheel" parent="base_link" radius="${drive_wheel_r}" width="0.05">
    <origin rpy="-6.123E-17 0 0" xyz="${BASE_R} 0.0 ${drive_wheel_r - agv_height/2 - hollow_h}" />
  </xacro:wheel>
  <xacro:wheel name="r_wheel" parent="base_link" radius="${drive_wheel_r}" width="0.05">
    <origin rpy="-6.123E-17 0 0" xyz="${BASE_R*-1} 0.0 ${drive_wheel_r - agv_height/2 - hollow_h}" />
  </xacro:wheel>

  <xacro:dummy_wheel name="lf_wheel" parent="base_link" x_loc="${BASE_DUMMY_R}" y_loc="0.4275">
  </xacro:dummy_wheel>
  <xacro:dummy_wheel name="rf_wheel" parent="base_link" x_loc="${BASE_DUMMY_R*-1}" y_loc="0.4275">
  </xacro:dummy_wheel>
  <xacro:dummy_wheel name="lr_wheel" parent="base_link" x_loc="${BASE_DUMMY_R}" y_loc="-0.42475">
  </xacro:dummy_wheel>
  <xacro:dummy_wheel name="rr_wheel" parent="base_link" x_loc="${BASE_DUMMY_R*-1}" y_loc="-0.42475">
  </xacro:dummy_wheel>

  <!-- Transmission -->
  <transmission name="rod_front_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="rod_front_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="rod_front_linear_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="rod_rare_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="rod_rare_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="rod_rare_linear_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</robot>
