<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
       name="agv2" >

  <!-- common stuff -->
  <xacro:include filename="$(find agv2_description)/urdf/shelf.gazebo.xacro" />
  <xacro:include filename="$(find agv2_description)/urdf/common.xacro" />
  <xacro:include filename="$(find agv2_description)/urdf/materials.urdf.xacro" />
<!--
  <xacro:include filename="$(find agv2_description)/urdf/controller.gazebo" />
-->
<!--
  <xacro:include filename="$(find agv2_description)/urdf/wheel_shelf.urdf.xacro" />
-->
<!--
  <xacro:include filename="$(find agv2_description)/urdf/laser.urdf.xacro" />
  <xacro:include filename="$(find agv2_description)/urdf/laser.gazebo.xacro" />
-->

  <link name="base_footprint"/>

  <!-- Base -->
  <property name="agv_height" value="0.268" />
  <property name="hollow_h" value="0.34" />
  <joint name="base_joint" type="fixed">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" velocity="0.5"/>
    <origin xyz="0 0 ${hollow_h}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  <link name="base_link">
    <inertial>
      <origin rpy="${M_PI/2} 0 0" xyz="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.0006699485" ixy="0.0" ixz="0.0" iyy="0.0010901" iyz="0.0" izz="0.0004378"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <mesh filename="package://agv2_description/meshes/pallet_spring_supp_brk_100kg.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <mesh filename="package://agv2_description/meshes/pallet_spring_supp_brk_100kg.stl" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>
  </link>

  <!-- wheel -->
  <property name="BASE_DUMMY_R" value="0.553"/>

<!--
  <xacro:dummy_wheel name="lf_wheel" parent="base_link" x_loc="${BASE_DUMMY_R}" y_loc="0.592">
  </xacro:dummy_wheel>
  <xacro:dummy_wheel name="rf_wheel" parent="base_link" x_loc="${BASE_DUMMY_R*-1}" y_loc="0.592">
  </xacro:dummy_wheel>
  <xacro:dummy_wheel name="lr_wheel" parent="base_link" x_loc="${BASE_DUMMY_R}" y_loc="-0.592">
  </xacro:dummy_wheel>
  <xacro:dummy_wheel name="rr_wheel" parent="base_link" x_loc="${BASE_DUMMY_R*-1}" y_loc="-0.592">
  </xacro:dummy_wheel>
-->
<!--
  <joint name="screen_joint" type="fixed"> ${drive_wheel_r - agv_height/2 - hollow_h} ${shaft_h + dummy_r - agv_height/2 - hollow_h}
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="-3.1415" upper="3.1415" velocity="0.5"/>
    <origin xyz="0 -0.01 0.3" rpy="${0.1745*6} 0 0"/>
    <parent link="chest_link"/>
    <child link="screen_link"/>
  </joint>

  <link name="screen_link">
    <visual>
      <origin xyz="0 -0.055 0" rpy="0 0 0" />
      <geometry>
        <cylinder length="0.01" radius="0.09"/>
      </geometry>
      <material name="Orange"/>
    </visual>
  </link>
-->

</robot>
