<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="wheel" params="name parent *origin radius width">
    <link name="${name}_link">
        <xacro:cylinder_inertial mass="0.1" radius="${radius}" length="${width}">
          <origin rpy="0 ${M_PI/2} 0" xyz="0 0 0" />
        </xacro:cylinder_inertial>
      <visual>
        <origin rpy="0 ${M_PI/2} 0" xyz="0 0 0" />
        <geometry>
          <cylinder length="${width}" radius="${radius}"/>
        </geometry>
        <material name="">
          <color rgba="0.086 0.506 0.767 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 ${M_PI/2} 0" xyz="0 0 0" />
        <geometry>
          <cylinder length="${width}" radius="${radius}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_joint" type="continuous">
      <insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${name}_link" />
      <axis xyz="1 0 0" />
    <limit effort="108.85" velocity="34.8" /></joint>
  </xacro:macro>
  <property name="dummy_r" value="0.0381" />
  <property name="dummy_w" value="0.033" />
  <property name="shaft_h" value="0.0695" />
  <property name="shaft_w" value="${0.033 + 0.02}" />
  <xacro:macro name="dummy_wheel" params="name parent x_loc x_dir y_loc y_dir">
    <link name="${name}_shaft_link">
        <xacro:box_inertial mass="4.0" x="${shaft_w}" y="${shaft_w}" z="${shaft_h}">
          <origin rpy="0 0 0" xyz="0 0 0" />
        </xacro:box_inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
          <box size="${shaft_w} ${shaft_w} ${shaft_h}"/>
        </geometry>
        <material name="">
          <color rgba="0.086 0.506 0.767 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
          <box size="${shaft_w} ${shaft_w} ${shaft_h}"/>
        </geometry>
        <material name="">
          <color rgba="0.086 0.506 0.767 1" />
        </material>
      </collision>
    </link>
    <link name="${name}_dummy_wheel">
        <xacro:cylinder_inertial mass="4.0" radius="${dummy_r}" length="${dummy_w}">
          <origin rpy="0 ${M_PI/2} 0" xyz="0 0 0" />
        </xacro:cylinder_inertial>
      <visual>
        <origin rpy="0 ${M_PI/2} 0" xyz="0 0 0" />
        <geometry>
          <cylinder length="${dummy_w}" radius="${dummy_r}"/>
        </geometry>
        <material name="">
          <color rgba="0.086 0.506 0.767 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 ${M_PI/2} 0" xyz="0 0 0" />
        <geometry>
          <cylinder length="${dummy_w}" radius="${dummy_r}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_joint_shaft" type="continuous">
      <origin rpy="-6.123E-17 0 0" xyz="${(x_loc - shaft_w/2)*x_dir} ${(y_loc - shaft_w/2)*y_dir} ${(agv_height + 0.01)*-1}" />
      <parent link="${parent}" />
      <child link="${name}_shaft_link" />
      <axis xyz="0 0 1" />
      <dynamics damping="0.9" friction="0.9" />
    </joint>
    <joint name="${name}_joint_roller" type="continuous">
      <origin xyz="0 ${shaft_w/2} ${-shaft_h/2}" rpy="0 0 0" />
      <parent link="${name}_shaft_link" />
      <child link="${name}_dummy_wheel" />
      <axis xyz="1 0 0" />
    </joint>
    <gazebo reference="${name}_dummy_wheel">
      <kp>500000.0</kp>
      <kd>10.0</kd>
      <mu1>0.01</mu1>
      <mu2>0.01</mu2>
      <material>Gazebo/WoodPallet</material>
    </gazebo>
    <gazebo reference="${name}_shaft_link">
      <mu1>50</mu1>
      <mu2>10</mu2>
      <dampingFactor>0.1</dampingFactor>
      <fdir1>0 0 1</fdir1>
    </gazebo>
  </xacro:macro>
</robot>
