<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="wheel" params="name parent *origin scx scy scz">
    <link name="${name}_link">
      <inertial>
        <origin rpy="0 0 ${M_PI/2}" xyz="0 0 0" />
        <mass value="4.3542" />
        <inertia ixx="0.0045" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.0045" />
      </inertial>
      <visual>
        <origin rpy="0 0 ${M_PI/2}" xyz="0 0 0" />
        <geometry>
          <mesh filename="package://agv2_description/meshes/l_wheel_link.STL" scale="${scx} ${scy} ${scz}"/>
        </geometry>
        <material name="">
          <color rgba="0.086 0.506 0.767 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 ${M_PI/2}" xyz="0 0 0" />
        <geometry>
          <mesh filename="package://agv2_description/meshes/l_wheel_link.STL" scale="${scx} ${scy} ${scz}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_joint" type="continuous">
      <insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${name}_link" />
      <axis xyz="1 0 0" />
    <limit effort="108.85" velocity="34.8" /></joint>
  </xacro:macro>

  <property name="roller_l" value="0.01" />
  <property name="dummy_r" value="0.005" />
  <xacro:macro name="dummy_wheel" params="name parent *origin radius">
    <link name="${name}_link">
        <xacro:cylinder_inertial mass="0.1" radius="${radius}" length="${roller_l}">
          <origin rpy="0 ${M_PI/2} 0" xyz="0 0 0" />
        </xacro:cylinder_inertial>
      <visual>
        <origin rpy="0 ${M_PI/2} 0" xyz="0 0 0" />
        <geometry>
          <cylinder length="${roller_l}" radius="${radius}"/>
        </geometry>
        <material name="">
          <color rgba="0.086 0.506 0.767 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 ${M_PI/2} 0" xyz="0 0 0" />
        <geometry>
          <cylinder length="${roller_l}" radius="${radius}"/>
        </geometry>
      </collision>
    </link>
    <link name="${name}_dummy">
        <xacro:cylinder_inertial mass="0.1" radius="${dummy_r}" length="${radius-hollow_h}">
          <origin rpy="0 0 0" xyz="0 0 0" />
        </xacro:cylinder_inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
          <cylinder length="${radius-hollow_h}" radius="${dummy_r}"/>
        </geometry>
        <material name="">
          <color rgba="0.086 0.506 0.767 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
          <cylinder length="${radius-hollow_h}" radius="${dummy_r}"/>
        </geometry>
        <material name="">
          <color rgba="0.086 0.506 0.767 1" />
        </material>
      </collision>
    </link>
    <joint name="${name}_joint_shaft" type="continuous">
      <insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${name}_dummy" />
      <axis xyz="0 0 1" />
    </joint>
    <joint name="${name}_joint_roller" type="continuous">
      <origin xyz="0 ${radius} ${radius-hollow_h}" rpy="0 0 0" />
      <parent link="${name}_dummy" />
      <child link="${name}_link" />
      <axis xyz="1 0 0" />
    </joint>
    <gazebo reference="${name}_link">
      <kp>500000.0</kp>
      <kd>10.0</kd>
      <mu1>0.01</mu1>
      <mu2>0.01</mu2>
    </gazebo>
    <gazebo reference="${name}_link_dummy">
      <mu1>50</mu1>
      <mu2>10</mu2>
      <dampingFactor>0.1</dampingFactor>
      <fdir1>0 0 1</fdir1>
    </gazebo>
  </xacro:macro>
</robot>
